server:
  port: 8080


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: r2dbc:h2:file:./db/bot;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
